const hikes = [
  {
    name: "Sturtevant Falls Trail",
    location: "Santa Anita Canyon",
    distance: 3.7,
    elevationGain: 830,
    tags: ["water", "scenic"],
    image: "assets/sturtevant-falls-tujunga.jpg",
  },
  {
    name: "Punchbowls via Santa Paula and Last Chance Trail",
    location: "Santa Paula",
    distance: 6.6,
    elevationGain: 1100,
    tags: ["water", "scenic", "grueling"],
    image: "assets/Punchbowls via Santa Paula and Last Chance Trail.jpg",
  },
  {
    name: "Bridge to Nowhere via East Fork",
    location: "Azusa",
    distance: 10.1,
    elevationGain: 900,
    tags: ["water", "scenic"],
    image: "assets/Bridge to Nowhere via East Fork.jpg",
  },
  {
    name: "Eaton Canyon Trail",
    location: "Pasadena",
    distance: 3.5,
    elevationGain: 375,
    tags: ["water"],
    image: "assets/Eaton Canyon Trail.jpg",
  },
  {
    name: "Saigon Trail",
    location: "Newport Beach",
    distance: 0.5,
    elevationGain: 150,
    tags: ["scenic"],
    image: "assets/Saigon Trail.jpg",
  },
  {
    name: "Switzer Falls via Gabrielino Trail",
    location: "Tujunga",
    distance: 4.3,
    elevationGain: 650,
    tags: ["water", "scenic"],
    image: "assets/Switzer Falls via Gabrielino Trail.webp",
  },
  {
    name: "Escondido Falls Trail",
    location: "Malibu",
    distance: 3.8,
    elevationGain: 620,
    tags: ["water", "scenic"],
    image: "assets/Escondido Falls Trail.jpg",
  },
  {
    name: "Strawberry Peak via Redbox Canyon",
    location: "Angeles National Forest",
    distance: 7.2,
    elevationGain: 1500,
    tags: ["peak", "scenic"],
    image: "assets/Strawberry Peak via Redbox Canyon.jpg",
  },
  {
    name: "Strawberry Peak via Mountaineer's Route",
    location: "Angeles National Forest",
    distance: 6.0,
    elevationGain: 1500,
    tags: ["peak", "grueling"],
    image: "assets/Strawberry Peak via Mountaineer's Route.jpg",
  },
  {
    name: "Sandstone Peak via Mishe Mokwa Loop",
    location: "Malibu",
    distance: 6.2,
    elevationGain: 1600,
    tags: ["peak", "scenic"],
    image: "assets/Sandstone Peak via Mishe Mokwa Loop.jpg",
  },
  {
    name: "Mount San Jacinto via Cactus to Clouds",
    location: "Palm Springs",
    distance: 21.0,
    elevationGain: 10400,
    tags: ["peak", "grueling"],
    image: "assets/c2c.jpg",
  },
  {
    name: "Mount San Jacinto via Tramway",
    location: "Palm Springs",
    distance: 11.0,
    elevationGain: 2400,
    tags: ["peak", "scenic"],
    image: "assets/Mount San Jacinto via Tramway.webp",
  },
  {
    name: "Mount San Jacinto via Devil's Slide Trail",
    location: "Idyllwild",
    distance: 15.4,
    elevationGain: 4500,
    tags: ["peak", "grueling"],
    image: "assets/Mount San Jacinto via Devil's Slide Trail.jpg",
  },
  {
    name: "Mount Baldy via Devil's Backbone",
    location: "Mt. Baldy",
    distance: 7.5,
    elevationGain: 2350,
    tags: ["peak", "scenic"],
    image: "assets/devils-backbone-mt-baldy.webp",
  },
  {
    name: "Mount Baldy via Baldy Bowl",
    location: "Mt. Baldy",
    distance: 9.0,
    elevationGain: 3900,
    tags: ["peak", "grueling"],
    image: "assets/baldybowl.jpg",
  },
  {
    name: "Mount San Gorgonio via Vivian Creek",
    location: "Forest Falls",
    distance: 17.2,
    elevationGain: 5600,
    tags: ["peak", "grueling"],
    image: "assets/Mount San Gorgonio via Vivian Creek.jpg",
  },
  {
    name: "Mount San Gorgonio via South Fork",
    location: "Angelus Oaks",
    distance: 20.5,
    elevationGain: 4800,
    tags: ["peak"],
    image: "assets/Mount San Gorgonio via South Fork.jpg",
  },
  {
    name: "Iron Mountain via Heaton Flats",
    location: "Azusa",
    distance: 14.0,
    elevationGain: 7200,
    tags: ["peak", "grueling"],
    image: "assets/Iron Mountain via Heaton Flats.webp",
  },
  {
    name: "Cucamonga Peak via Icehouse Canyon",
    location: "Mt. Baldy",
    distance: 11.6,
    elevationGain: 4300,
    tags: ["peak", "grueling"],
    image: "assets/Cucamonga Peak via Icehouse Canyon.webp",
  },
  {
    name: "Rattlesnake Peak via Rattlesnake Peak Trail",
    location: "Azusa",
    distance: 9.0,
    elevationGain: 3700,
    tags: ["peak", "grueling"],
    image: "assets/Rattlesnake Peak via Rattlesnake Peak Trail.jpg",
  },
  {
    name: "Mount Wilson via Mount Wilson Trail",
    location: "Sierra Madre",
    distance: 14.0,
    elevationGain: 4700,
    tags: ["peak", "grueling"],
    image: "assets/Mount Wilson via Mount Wilson Trail.webp",
  },
  {
    name: "Rancho Palos Verdes Coastal Trail",
    location: "Palos Verdes",
    distance: 5.0,
    elevationGain: 500,
    tags: ["scenic"],
    image: "assets/Rancho Palos Verdes Coastal Trail.jpg",
  },
  {
    name: "Palos Verdes Coastline Trail",
    location: "Palos Verdes",
    distance: 4.5,
    elevationGain: 400,
    tags: ["scenic", "water"],
    image: "assets/Palos Verdes Coastline Trail.webp",
  },
  {
    name: "Topanga Lookout",
    location: "Topanga",
    distance: 2.0,
    elevationGain: 520,
    tags: ["scenic"],
    image: "assets/Topanga Lookout.jpg",
  },
  {
    name: "Corral Canyon",
    location: "Malibu",
    distance: 2.5,
    elevationGain: 500,
    tags: ["scenic"],
    image: "assets/Corral Canyon.jpg",
  },
  {
    name: "Tuna Canyon Trails",
    location: "Malibu",
    distance: 3.5,
    elevationGain: 600,
    tags: ["scenic"],
    image: "assets/Tuna Canyon Trails.webp",
  },
  {
    name: "East Observatory Trail",
    location: "Griffith Park",
    distance: 1.5,
    elevationGain: 400,
    tags: ["scenic"],
    image: "assets/East Observatory Trail.webp",
  },
  {
    name: "Hollywood Sign via Canyon Drive",
    location: "Griffith Park",
    distance: 6.0,
    elevationGain: 1100,
    tags: ["scenic"],
    image: "assets/Hollywood Sign via Canyon Drive.jpg",
  }
];
